accounts/urls.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView


urlpatterns = [
    path('signup/', CreateView.as_view(
        template_name='accounts/signup.html',
        form_class=UserCreationForm,
        success_url='/',
    ), name='signup'),
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='accounts/login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('janken.urls')),
]

janken/urls.py
from django.urls import path
from . import views

app_name = 'janken'

urlpatterns = [
    path('', views.top, name='top'),
    path('<int:opponent_id>/', views.opponent_detail, name='op_detail'),
    path('new/', views.opponent_new, name='op_new'),
    path('<int:opponent_id>/register/', views.game_register, name='game_register'),
]

janken/models.py
from django.db import models
from django.db.models.base import Model
from django.conf import settings

# Create your models here.

class Opponent(models.Model):
    name = models.CharField('対戦相手', max_length=12)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='作成者',
        on_delete=models.CASCADE
    )

    class Meta:
        db_table = 'Opponents'

    def __str__(self):
        return self.name

class Game(models.Model):
    HANDS = (
        ('0', 'グー'),
        ('1', 'チョキ'),
        ('2', 'パー'),
    )
    opponent = models.ForeignKey(
        Opponent,
        verbose_name='対戦相手',
        on_delete=models.CASCADE
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='作成者',
        on_delete=models.CASCADE
    )
    opponent_hand = models.CharField(
        '相手の手',
        max_length=1,
        choices=HANDS
    )
    my_hand = models.CharField(
        '自分の手',
        max_length=1,
        choices=HANDS
    )
    result = models.CharField(
        '対戦結果',
        max_length=4,
    )

    class Meta:
        db_table = 'games'

    def __str__(self):
        return  f'{self.opponent} - {self.created_by}'

janken/forms.py
from django import forms
from django.db import models
from django.db.models.base import Model
from django.forms import fields
from .models import Opponent, Game

class OpponentForm(forms.ModelForm):
    class Meta:
        model = Opponent
        fields = ('name',)

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('opponent_hand', 'my_hand')

janken/views.py
from janken.forms import GameForm, OpponentForm
from janken.models import Opponent, Game
from django.http.response import HttpResponse, HttpResponseForbidden
from django.db.models import Count
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
# Create your views here.

# トップページ用View
def top(request):
    user_id = request.user.id
    opponents = Opponent.objects.all()
    context = {
        'opponents': opponents
    }
    return render(request, 'janken/top.html', context)

@login_required
def opponent_detail(request, opponent_id):
    user_id = request.user.id
    opponent = get_object_or_404(Opponent, pk=opponent_id)
    form = GameForm()
    games = Game.objects.filter(opponent=opponent_id)
    win_rate = round(games.filter(result='勝ち').count() / games.exclude(result='あいこ').count() * 100, 1)
    lose_rate = 100 - win_rate
    draw_rate = round(games.filter(result='あいこ').count() / games.count() * 100, 1)
    if opponent.created_by.id == user_id:
        context = {
            'opponent': opponent,
            'form': form,
            'win_rate': win_rate,
            'lose_rate': lose_rate,
            'draw_rate': draw_rate,
        }
        return render(request, 'janken/opponent_detail.html', context)
    else:
        return HttpResponseForbidden('このページの閲覧は許可されていません')


@login_required
def opponent_new(request):
    if request.method == 'POST':
        form = OpponentForm(request.POST)
        if form.is_valid():
            opponent = form.save(commit=False)
            opponent.created_by = request.user
            opponent.save()
            return redirect('janken:top')
    else:
        form = OpponentForm()
        context = {
            'form': form
        }
        return render(request, 'janken/opponent_new.html', context)

@login_required
def game_register(request, opponent_id):
        if request.method == 'POST':
            form = GameForm(request.POST)
            if form.is_valid():
                game = form.save(commit=False)
                game.opponent_id = opponent_id
                game.created_by = request.user
                # 勝敗判定
                if (int(game.my_hand) - int(game.opponent_hand) + 3) % 3 == 2:
                    game.result = '勝ち'
                elif (int(game.my_hand) - int(game.opponent_hand) + 3) % 3 == 1:
                    game.result = '負け'
                else:
                    game.result = 'あいこ'
                game.save()
                return redirect('janken:op_detail', opponent_id)
        else:
            return HttpResponseForbidden('正規の手順を踏んでください')

templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>ログイン</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="ログイン" %}
  </form>
{% endblock main %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
  <h1>新規登録</h1>

  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="登録" %}
  </form>
{% endblock main %}

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="UTF-8">
    <title>Janken-Lab</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block exheader %}{% endblock exheader%}
  </head>

  <body>
    <nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
      <div class="container justify-content-between">
        <a class="navbar-brand" href="/">Janken-Lab</a>
        <ul class="navbar-nav mr-md-2">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link">{{ user.username }}</a>
              <a class="nav-link" href="{% url 'logout' %}">ログアウト</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">会員登録</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main>
      <div class="container">
        {% block main %}{% endblock main %}
      </div>
    </main>
    
  </body>

</html>

templates/janken/opponent_detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block main %}
  <div class="sub-welcome">
    <h1 class="sub-title">VS</h1>
    <h1 class="title">{{ opponent.name }}</h1>
  </div>

  <div class="info-box">
    <div class="win-rate">
      <p>勝率</p>
      <p>win:
        {{ win_rate }}
        %</p>
      <p>lose:
        {{ lose_rate }}
        %</p>
      <p>draw:
        {{ draw_rate }}
        %</p>
    </div>
    <div class="guess-ophand">
      <p>予想</p>
      {% for hand in guess_ophand %}
        <p>{{ hand.opponent_hand }}</p>
      {% endfor %}
    </div>
  </div>

  <div class="game-form">
    <form action="{% url 'janken:game_register' opponent.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-submit">
        追加
      </button>
    </form>
  </div>
{% endblock main %}

templates/janken/opponent_new.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block main %}
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-submit">登録</button>

  </form>
  
{% endblock main %}

templates/janken/top.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <div class="welcome">
    <h1 class="title">ようこそ、Janken-Labへ！</h1>
    <p class="subtitle">じゃんけんの勝率をあげましょう</p>
    <a href="{% url 'janken:op_new' %}" class="btn btn-color">対戦相手を追加</a>
  </div>

  {% if user.is_authenticated %}
    {% if opponents %}
      <ul class="opponents-list">
        <li class="opponents-header">対戦相手一覧</li>
        {% for opponent in opponents %}
          {% if opponent.created_by_id == user.id %}
            <li>
              <a href="{% url 'janken:op_detail' opponent.id %}" class="opponent">
                {{ opponent.name }}
              </a>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    {% else %}
      <p class="message">対戦相手がまだいません.</p>
    {% endif %}
  {% endif %}

{% endblock main %}